"""Parseur du relevé Trading212 (Activity Statement PDF → valeur + composition)."""

from __future__ import annotations

from app.services.finance.trading212 import parse_trading212_statement

# Extrait fidèle du texte pypdf (mode plain) d'un Activity Statement Trading212.
_TEXT = """CUSTOMER ID9262934 CUSTOMER NAMEGermain De Sousa
Activity statement
Generated by Trading 212 Markets Ltd. on 18 June 2026, covering from 31.05.2026 21:00 (UTC) to 16.06.2026 20:59 (UTC).
Overview
Deposits €0.00
Account value €903.80
1/7
Invest account - open positions summary
Pending orders
INSTRUMENT ISIN INSTRUMENT CURRENCY ORDER ID TYPE DIRECTION EXPIRATION QUANTITY LIMIT PRICE STOP PRICE VALUE
No data available
Open positions
INSTRUMENT ISIN INSTRUMENT CURRENCY QUANTITY AVERAGE PRICE PRICE RETURN VALUE FX RATE RETURN VALUE
BAG GB00B6XZKY75 GBX 33.51679975 657.33930937 647 -346.54 21685.3694 86.479 €-1.78 €250.76
BAH US0995021062 USD 2.06925832 81.39148137 74.21 -14.86 153.5597 1.16096 €-13.82 €132.27
INVA US45781M1018 USD 3.56997519 23.58839922 22.61 -3.49 80.7171 1.16096 €-3.51 €69.53
SGLN IE00B4ND3602 GBX 3.46738225 6970.51212049 6255 -2480.95 21688.476 86.479 €-26.36 €250.79
3/7
CUSTOMER ID9262934 CUSTOMER NAMEGermain De Sousa
Invest account - cash breakdown
"""


def test_parse_account_value():
    out = parse_trading212_statement(_TEXT)
    assert out["account_value"] == 903.80
    assert out["devise"] == "EUR"
    assert out["date"] == "2026-06-16"   # fin de période


def test_parse_open_positions():
    out = parse_trading212_statement(_TEXT)
    assert [p["instrument"] for p in out["positions"]] == ["BAG", "BAH", "INVA", "SGLN"]
    bag = out["positions"][0]
    assert bag["isin"] == "GB00B6XZKY75"
    assert bag["currency"] == "GBX"
    assert bag["quantity"] == 33.51679975
    assert bag["value_eur"] == 250.76   # dernière colonne € = valeur de la position


def test_positions_value_plus_known_cash_reconciles():
    out = parse_trading212_statement(_TEXT)
    positions_total = round(sum(p["value_eur"] for p in out["positions"]), 2)
    assert positions_total == 703.35              # 250.76+132.27+69.53+250.79
    assert round(positions_total + 200.45, 2) == out["account_value"]  # + cash EUR


def test_parse_empty_text():
    out = parse_trading212_statement("rien d'utile")
    assert out["account_value"] is None
    assert out["positions"] == []
