"""journal mood_entry

Revision ID: 262e83c85856
Revises: n153robottables
Create Date: 2026-06-09 16:04:49.622350
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '262e83c85856'
down_revision: Union[str, None] = 'n153robottables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('humeur', sa.Integer(), nullable=False),
    sa.Column('energie', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_entry_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_entry_date'))

    op.drop_table('mood_entry')
    # ### end Alembic commands ###
