"""window_plan

Revision ID: 495cbf46bce0
Revises: l530bookserietome
Create Date: 2026-07-23 14:53:54.953408
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '495cbf46bce0'
down_revision: Union[str, None] = 'l530bookserietome'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('window_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('poids_used', sa.Float(), nullable=True),
    sa.Column('food_set', sa.JSON(), nullable=True),
    sa.Column('shopping_list', sa.JSON(), nullable=True),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('debt_series', sa.JSON(), nullable=True),
    sa.Column('warning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('window_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_window_plan_anchor_date'), ['anchor_date'], unique=True)

    # ### end Alembic commands ###
    # NB: l'autogénération a aussi détecté `buffett_run_result_bak_20260715_135731`
    # (table de sauvegarde manuelle, hors modèles) et `apscheduler_jobs` (gérée par
    # APScheduler lui-même, hors SQLModel.metadata) comme "removed" — non lié à cette
    # tâche, retiré intentionnellement pour que la migration ne porte que window_plan.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('window_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_window_plan_anchor_date'))

    op.drop_table('window_plan')
    # ### end Alembic commands ###
