"""finance_settings

Revision ID: d69434536a1c
Revises: d2f134f7b75c
Create Date: 2026-06-03 11:55:11.781994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd69434536a1c'
down_revision: Union[str, None] = 'd2f134f7b75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taux_plus_value_pct', sa.Float(), nullable=False),
    sa.Column('taux_dividende_pct', sa.Float(), nullable=False),
    sa.Column('devise_affichage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('finance_settings')
