"""musique tracks

Revision ID: d2f280517703
Revises: 9c82888c950b
Create Date: 2026-06-09 23:16:03.187392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2f280517703'
down_revision: Union[str, None] = '9c82888c950b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duree_sec', sa.Integer(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_track_path'), ['path'], unique=True)

    op.create_table('track_ambiance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('ambiance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['music_track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_ambiance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_ambiance_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_ambiance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_ambiance_track_id'))

    op.drop_table('track_ambiance')
    with op.batch_alter_table('music_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_track_path'))

    op.drop_table('music_track')
    # ### end Alembic commands ###
