"""add lieu_voyage and duffel_price_cache tables

Revision ID: 763cb2d89706
Revises: i620garderobeimage
Create Date: 2026-07-01 12:44:57.793105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '763cb2d89706'
down_revision: Union[str, None] = 'i620garderobeimage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duffel_price_cache',
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origine_iata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination_iata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duree_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('lieu_voyage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visite', sa.Boolean(), nullable=False),
    sa.Column('aeroport_iata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jours_min', sa.Integer(), nullable=True),
    sa.Column('jours_max', sa.Integer(), nullable=True),
    sa.Column('cout_jour_estime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    op.drop_table('lieu_voyage')
    op.drop_table('duffel_price_cache')
    # ### end Alembic commands ###
