"""skincare module

Revision ID: d2f134f7b75c
Revises: 0033b95bc1df
Create Date: 2026-06-02 00:59:34.802452
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2f134f7b75c'
down_revision: Union[str, None] = '0033b95bc1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skincare_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_jour', sa.Date(), nullable=False),
    sa.Column('moment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produits_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_jour', 'moment')
    )
    op.create_table('skincare_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('frequence_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequence_jours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequence_n', sa.Integer(), nullable=True),
    sa.Column('apres_douche', sa.Boolean(), nullable=False),
    sa.Column('soir_seulement', sa.Boolean(), nullable=False),
    sa.Column('pas_avant_soleil', sa.Boolean(), nullable=False),
    sa.Column('duree_min', sa.Integer(), nullable=False),
    sa.Column('stock_qte', sa.Float(), nullable=True),
    sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_ouverture', sa.Date(), nullable=True),
    sa.Column('date_peremption', sa.Date(), nullable=True),
    sa.Column('cout', sa.Float(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skincare_product')
    op.drop_table('skincare_log')
    # ### end Alembic commands ###
