"""add_budget_habitudes_livres_cuisine_scheduler

Revision ID: 0033b95bc1df
Revises: f6a7b8c9d0e1
Create Date: 2026-05-31 11:57:01.247278
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite
from sqlalchemy import inspect as sa_inspect


def _table_exists(name: str) -> bool:
    bind = op.get_bind()
    return name in sa_inspect(bind).get_table_names()


def _create_if_missing(table_name: str, *args, **kwargs):
    if not _table_exists(table_name):
        op.create_table(table_name, *args, **kwargs)


def _drop_if_exists(table_name: str):
    if _table_exists(table_name):
        op.drop_table(table_name)

# revision identifiers, used by Alembic.
revision: str = '0033b95bc1df'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_if_missing('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auteur', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('couverture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('budget_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('couleur', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['budget_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cible', sa.Float(), nullable=False),
    sa.Column('frequence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_auto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('temps_prep', sa.Integer(), nullable=False),
    sa.Column('temps_cuisson', sa.Integer(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('shopping_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semaine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rayon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('achete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('book_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('book_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('texte', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('budget_envelope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('mois', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['budget_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'mois')
    )
    _create_if_missing('budget_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['budget_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('budget_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('marchand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('compte', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['budget_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('habit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date')
    )
    _create_if_missing('meal_plan_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semaine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('repas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('reading_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('page_debut', sa.Integer(), nullable=True),
    sa.Column('page_fin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_if_missing('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('aliment_id', sa.Integer(), nullable=True),
    sa.Column('nom_libre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['aliment_id'], ['aliment.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _drop_if_exists('livre')
    if _table_exists('habitude'):
        with op.batch_alter_table('habitude', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_habitude_nom'))
        _drop_if_exists('habitude')
    if _table_exists('depense'):
        with op.batch_alter_table('depense', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_depense_date'))
        _drop_if_exists('depense')
    _drop_if_exists('recette')
    if _table_exists('habitude_log'):
        with op.batch_alter_table('habitude_log', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_habitude_log_date'))
            batch_op.drop_index(batch_op.f('ix_habitude_log_habitude_id'))
        _drop_if_exists('habitude_log')
    # TEXT → AutoString is a no-op in SQLite, skip to avoid temp table conflicts
    with op.batch_alter_table('buffett_run_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_entry_ticker'))
        batch_op.create_index(batch_op.f('ix_buffett_run_result_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buffett_run_result_ticker'), ['ticker'], unique=True)

    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_evenement_recurrence_id', 'regle_recurrence', ['recurrence_id'], ['id'])

    with op.batch_alter_table('regle_recurrence', schema=None) as batch_op:
        batch_op.alter_column('weekdays',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regle_recurrence', schema=None) as batch_op:
        batch_op.alter_column('weekdays',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evenement_recurrence_id', type_='foreignkey')

    with op.batch_alter_table('buffett_run_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buffett_run_result_ticker'))
        batch_op.drop_index(batch_op.f('ix_buffett_run_result_run_id'))
        batch_op.create_index(batch_op.f('ix_watchlist_entry_ticker'), ['ticker'], unique=1)

    with op.batch_alter_table('buffett_run', schema=None) as batch_op:
        batch_op.alter_column('erreur',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('resume',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('habitude_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('habitude_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('fait', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['habitude_id'], ['habitude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habitude_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitude_log_habitude_id'), ['habitude_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habitude_log_date'), ['date'], unique=False)

    op.create_table('recette',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(), nullable=False),
    sa.Column('ingredients', sqlite.JSON(), nullable=True),
    sa.Column('etapes', sqlite.JSON(), nullable=True),
    sa.Column('portions', sa.INTEGER(), nullable=True),
    sa.Column('duree_min', sa.INTEGER(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.Column('devise', sa.VARCHAR(), nullable=False),
    sa.Column('categorie', sa.VARCHAR(), nullable=True),
    sa.Column('libelle', sa.VARCHAR(), nullable=True),
    sa.Column('moyen_paiement', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depense_date'), ['date'], unique=False)

    op.create_table('habitude',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(), nullable=False),
    sa.Column('cible_par_semaine', sa.INTEGER(), nullable=True),
    sa.Column('actif', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habitude', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitude_nom'), ['nom'], unique=False)

    op.create_table('livre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titre', sa.VARCHAR(), nullable=False),
    sa.Column('auteur', sa.VARCHAR(), nullable=True),
    sa.Column('statut', sa.VARCHAR(), nullable=False),
    sa.Column('pages', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.FLOAT(), nullable=True),
    sa.Column('date_debut', sa.DATE(), nullable=True),
    sa.Column('date_fin', sa.DATE(), nullable=True),
    sa.Column('commentaire', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe_ingredient')
    op.drop_table('reading_session')
    op.drop_table('meal_plan_entry')
    op.drop_table('habit_entry')
    op.drop_table('budget_transaction')
    op.drop_table('budget_rule')
    op.drop_table('budget_envelope')
    op.drop_table('book_quote')
    op.drop_table('book_note')
    op.drop_table('shopping_list_item')
    op.drop_table('recipe')
    op.drop_table('notification')
    op.drop_table('job_run')
    op.drop_table('habit')
    op.drop_table('budget_category')
    op.drop_table('book')
    # ### end Alembic commands ###
