"""initial schema

Revision ID: cd9aba577b3c
Revises: 
Create Date: 2026-05-15 03:36:00.979312
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd9aba577b3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proprietes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aliment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliment_nom'), ['nom'], unique=True)

    op.create_table('depense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categorie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('moyen_paiement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depense_date'), ['date'], unique=False)

    op.create_table('etude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sujet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duree_min', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etude', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etude_date'), ['date'], unique=False)

    op.create_table('evenement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('debut', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('lieu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evenement_debut'), ['debut'], unique=False)

    op.create_table('habitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cible_par_semaine', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habitude', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitude_nom'), ['nom'], unique=False)

    op.create_table('livre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auteur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('commentaire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesure_sante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mesure_sante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesure_sante_date'), ['date'], unique=True)

    op.create_table('plan_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('quantites', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_nutrition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_nutrition_date'), ['date'], unique=False)

    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('pmu', sa.Float(), nullable=True),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_broker'), ['broker'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_ticker'), ['ticker'], unique=False)

    op.create_table('recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('etapes', sa.JSON(), nullable=True),
    sa.Column('portions', sa.Integer(), nullable=True),
    sa.Column('duree_min', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exercices', sa.JSON(), nullable=True),
    sa.Column('duree_min', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seance_date'), ['date'], unique=False)

    op.create_table('snapshot_portefeuille',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('investit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_portefeuille', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_portefeuille_date'), ['date'], unique=True)

    op.create_table('tenue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tenue', sa.JSON(), nullable=True),
    sa.Column('ids', sa.JSON(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenue_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenue_history_date'), ['date'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('devise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frais', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_ticker'), ['ticker'], unique=False)

    op.create_table('vetement',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marque', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categorie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sous_categorie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matiere', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('couleur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('etat_propre', sa.Float(), nullable=True),
    sa.Column('usure_max', sa.Float(), nullable=True),
    sa.Column('portes', sa.Integer(), nullable=False),
    sa.Column('impermeable', sa.Boolean(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secteur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('croissance', sa.Float(), nullable=True),
    sa.Column('peg', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('chance_moat', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('achat', sa.Boolean(), nullable=False),
    sa.Column('trading_212', sa.Float(), nullable=True),
    sa.Column('bourse_direct', sa.Float(), nullable=True),
    sa.Column('bourse_direct_2', sa.Float(), nullable=True),
    sa.Column('ibkr', sa.Float(), nullable=True),
    sa.Column('secteurs_extra', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_entry_ticker'), ['ticker'], unique=True)

    op.create_table('habitude_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habitude_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fait', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habitude_id'], ['habitude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habitude_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitude_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habitude_log_habitude_id'), ['habitude_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitude_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habitude_log_habitude_id'))
        batch_op.drop_index(batch_op.f('ix_habitude_log_date'))

    op.drop_table('habitude_log')
    with op.batch_alter_table('watchlist_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_entry_ticker'))

    op.drop_table('watchlist_entry')
    op.drop_table('vetement')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_ticker'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))

    op.drop_table('transaction')
    with op.batch_alter_table('tenue_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenue_history_date'))

    op.drop_table('tenue_history')
    with op.batch_alter_table('snapshot_portefeuille', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_portefeuille_date'))

    op.drop_table('snapshot_portefeuille')
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seance_date'))

    op.drop_table('seance')
    op.drop_table('recette')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_ticker'))
        batch_op.drop_index(batch_op.f('ix_position_broker'))

    op.drop_table('position')
    with op.batch_alter_table('plan_nutrition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_nutrition_date'))

    op.drop_table('plan_nutrition')
    with op.batch_alter_table('mesure_sante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesure_sante_date'))

    op.drop_table('mesure_sante')
    op.drop_table('livre')
    with op.batch_alter_table('habitude', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habitude_nom'))

    op.drop_table('habitude')
    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evenement_debut'))

    op.drop_table('evenement')
    with op.batch_alter_table('etude', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etude_date'))

    op.drop_table('etude')
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depense_date'))

    op.drop_table('depense')
    with op.batch_alter_table('aliment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliment_nom'))

    op.drop_table('aliment')
    # ### end Alembic commands ###
